[package]
name = "day01"
version = "0.1.0"
authors = ["Kevin M Granger"]
edition = "2018"

[dependencies]
anyhow = "1.0.25"

[features]
part2 = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html